nutlink: init
blockfrost/openapi pull request #78
Opened 2021-06-09 13:01 UTC by mmahut

Initial work for the `/nutlink` endpoint.

2021-06-14 11:08 UTC, mmahut commented on swagger.yaml
> +    post:
```suggestion
```

2021-06-14 11:08 UTC, mmahut commented on swagger.yaml
> +    post:
```suggestion
```

2021-06-14 14:49 UTC, 1000101 commented on swagger.yaml
> +    post:
```suggestion
    get:
```

2021-06-14 14:51 UTC, 1000101 requested changes

2021-06-14 14:51 UTC, 1000101 commented on swagger.yaml
> +    post:
```suggestion
    get:
```

2021-06-14 14:51 UTC, 1000101 commented on swagger.yaml
> +    post:
```suggestion
    get:
```

2021-06-14 14:51 UTC, 1000101 commented on swagger.yaml
> +    post:
```suggestion
    get:
```

2021-06-14 14:51 UTC, 1000101 commented on swagger.yaml
> +    post:
```suggestion
    get:
```

2021-06-14 14:51 UTC, 1000101 commented on swagger.yaml
> +    post:
```suggestion
    get:
```

2021-06-14 14:51 UTC, 1000101 commented on swagger.yaml
> +    post:
```suggestion
    get:
```

2021-06-14 14:51 UTC, 1000101 commented on swagger.yaml
> +            type: integer
```suggestion
            type: string
```
Are you sure int won't overflow?

2021-06-14 15:06 UTC, 1000101 commented on swagger.yaml
> +          additionalProperties: true
```suggestion
          additionalProperties: true
```

do we need this if we don't define any specific requirements on the metadata object?

2021-06-14 15:09 UTC, 1000101 commented on swagger.yaml
> +        - metadata_hash
```suggestion
      required:
        - metadata_url
        - metadata_hash
        - metadata
```

I think metadata should always be present, despite the fact that they can be `null`

2021-06-14 15:10 UTC, 1000101 commented on swagger.yaml
> +      additionalProperties: true
```suggestion
      additionalProperties: true
```
Same as with the other addProps - is this needed?

2021-06-14 17:16 UTC, 1000101 commented on swagger.yaml
> +            type: string
```suggestion
            type: integer
```
Block height is integer.

2021-06-15 13:59 UTC, 1000101 commented on swagger.yaml
> +  /nutlink/{ticker}:
```suggestion
  /nutlink/tickers/{ticker}:
```
This route collides with `/nutlink/{address}`

2021-06-15 14:01 UTC, 1000101 requested changes

2021-06-15 14:01 UTC, 1000101 commented on swagger.yaml
> +  /nutlink/{ticker}/addresses:
```suggestion
  /nutlink/tickers/{ticker}/addresses:
```

Might also add additional `tickers` as the outher route collides with `/nutlink/{address}`

2021-06-15 14:52 UTC, 1000101 commented on swagger.yaml
> +      additionalProperties: true
Ok, seems to be needed as without explicitly specifying the object structure, the schema won't validate.

2021-06-15 14:54 UTC, 1000101 commented on swagger.yaml
> +          additionalProperties: true
My bad, definitely needed - without specifying the object structure it won't validate. So we either need this or explicitly define what's in metadata - I would vouch for the latter, but I'm not sure if this format is a standard.

2021-06-15 14:55 UTC, 1000101 commented on swagger.yaml
> +          nullable: true
```suggestion
          description: The cached metadata of the `metadata_url` file.
          additionalProperties: true
          nullable: true
```


My bad, definitely needed - without specifying the object structure it won't validate. So we either need this or explicitly define what's in metadata - I would vouch for the latter, but I'm not sure if this format is a standard.

2021-06-16 13:13 UTC, 1000101 requested changes

2021-06-16 13:13 UTC, 1000101 commented on swagger.yaml
> +            type: string
```suggestion
          latest_block:
            type: integer
```

2021-06-16 13:13 UTC, 1000101 commented on swagger.yaml
> +          - latest
```suggestion
          - latest_block
```

2021-06-16 13:13 UTC, 1000101 commented on swagger.yaml
> +          latest: "2657092"
```suggestion
          latest_block:
            type: integer
            description: Block height of the latest record
        required:
          - name
          - count
          - latest_block
      example:
        - asset: "ADAUSD"
          count: 1980038
          latest_block: 2657092
        - asset: "ADAEUR"
          count: 1980038
          latest_block: 2657092
        - asset: "ADABTC"
          count: 1980038
          latest_block: 2657092
```

2021-06-16 13:56 UTC, 1000101 commented on swagger.yaml
> +      type: object
```suggestion
      type: array
```

2021-06-16 17:00 UTC, merged